### ISSUE TITLE
Array.prototype.fill test unclear

### ISSUE THREAD

**Issue by erquhart** [tddbin/es6katas.org#9]
Lines 12-16 in the Array.prototype.fill kata:

```
it('fill only changes content, adds no new elements', function() {
  const arr = [undefined].fill(0);
    
  assert.deepEqual(arr, []);
});
```

There are a number of ways to get this passing, but I can't think of any that are meaningful for working with the `fill` method. What's the thought here?

**Comment by wolframkriesing** [comment]
The expectation is to get an empty array, the simplest thing should be removing the undefined, if you continue from the test above I hoped that this would become obvious, maybe you have a better suggestion? PRs welcome

is this maybe better?
```
it('fill only changes content, adds no new elements', function() {
  const arr = [undefined].fill(0);

  assert.deepEqual(arr, [0,0,0]);
});
```

**Comment by timabell** [comment]
This tripped me up too.

I think the issue is that it's a negative assertion, so it's hard to make it fail because whether you ask for it to fill beyond the end or not `fill` has the same output.

The only thing I can think of is to get users to fix the `assert` instead of the call to `fill`:

```
  it('fill only changes content, adds no new elements', function() {
    const arr = [1,2,3].fill(9,1,4); // tries to fill past end
    assert.deepEqual(arr, [1,9,9,9]); // fix this test
  });
```

On the plus side I learnt something about `fill` that will probably stick in my mind now!

It's also extra-confusing because [`fill`'s `end` argument is actually "stop before this zero-based index".](https://www.reddit.com/r/learnjavascript/comments/b10hvf/seem_to_be_off_by_1_with_arrayfill_with_the_end/)

**Comment by wolframkriesing** [comment]
The description above says "adds no new elements", and the expectation is to have an empty array. 
Is it possible, that the descriptions are not used as I intended them to be? They are intended to be the instruction for solving the test and make it pass. Just reading the test is half useful, I agree.

That's how I solved it. Sure, I am biased, but I also didnt try this kata for years, I guess.
```
  it('fill only changes content, adds no new elements', function() {
    const arr = [].fill(0);
    assert.deepEqual(arr, []);
  });
```

Any suggestion to make it better?
